[package]
name = "tint-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "tint"
path = "src/main.rs"

[dependencies]
tint-lexer = { path = "../tint-lexer" }
tint-ast = { path = "../tint-ast" }
tint-parser = { path = "../tint-parser" }
tint-runtime = { path = "../tint-runtime" }
tint-evaluator = { path = "../tint-evaluator" }
tint-semantics = { path = "../tint-semantics" }
base64 = "0.22"
