/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_domsession_free: (a: number, b: number) => void;
export const __wbg_tintrepl_free: (a: number, b: number) => void;
export const __wbg_uisession_free: (a: number, b: number) => void;
export const check: (a: number, b: number) => any;
export const domsession_dispatch: (a: number, b: number, c: number) => [number, number];
export const domsession_dispatch_frame: (a: number, b: number, c: number, d: number) => [number, number];
export const domsession_dispatch_http: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const domsession_hydrate_storage: (a: number, b: any) => [number, number];
export const domsession_new: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const domsession_reload: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const domsession_rerender: (a: number) => [number, number];
export const domsession_storage_snapshot: (a: number) => any;
export const domsession_take_http_requests: (a: number) => any;
export const render_ui: (a: number, b: number, c: number, d: number) => any;
export const run: (a: number, b: number, c: number, d: number) => any;
export const tint_version: () => [number, number];
export const tintrepl_eval: (a: number, b: number, c: number) => any;
export const tintrepl_new: () => number;
export const tintrepl_reset: (a: number) => void;
export const uisession_dispatch: (a: number, b: number, c: number) => any;
export const uisession_dispatch_frame: (a: number, b: number, c: number, d: number) => any;
export const uisession_dispatch_http: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => any;
export const uisession_hydrate_storage: (a: number, b: any) => [number, number];
export const uisession_new: (a: number, b: number, c: number, d: number) => number;
export const uisession_reload: (a: number, b: number, c: number, d: number, e: number) => any;
export const uisession_storage_snapshot: (a: number) => any;
export const uisession_take_http_requests: (a: number) => any;
export const uisession_tree: (a: number) => any;
export const wasm_bindgen_27a16a9810de17ac___convert__closures_____invoke___f64______true_: (a: number, b: number, c: number) => void;
export const wasm_bindgen_27a16a9810de17ac___convert__closures_____invoke___web_sys_2fd947709365e817___features__gen_KeyboardEvent__KeyboardEvent______true_: (a: number, b: number, c: any) => void;
export const wasm_bindgen_27a16a9810de17ac___convert__closures_____invoke___web_sys_2fd947709365e817___features__gen_KeyboardEvent__KeyboardEvent______true__27: (a: number, b: number, c: any) => void;
export const wasm_bindgen_27a16a9810de17ac___convert__closures_____invoke_______true_: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
