[package]
name = "tint-ir"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde_json = "1.0"
tint-lexer = { path = "../tint-lexer" }
serde = { version = "1.0", features = ["derive"] }
tint-ast = { path = "../tint-ast" }
tint-semantics = { path = "../tint-semantics" }

[dev-dependencies]
tint-lexer = { path = "../tint-lexer" }
tint-parser = { path = "../tint-parser" }
