[package]
name = "tint-ir"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tint-ast = { path = "../tint-ast" }
tint-semantics = { path = "../tint-semantics" }

[dev-dependencies]
tint-lexer = { path = "../tint-lexer" }
tint-parser = { path = "../tint-parser" }
