[package]
name = "rune-runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
rune-ast = { path = "../rune-ast" }
rune-parser = { path = "../rune-parser" }
rune-ir = { path = "../rune-ir" }
rune-lexer = { path = "../rune-lexer" }
rune-evaluator = { path = "../rune-evaluator" }

thiserror = "1.0"
async-trait = "0.1"
futures = "0.3"
