[package]
name = "rune-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rune"
path = "src/main.rs"

[dependencies]
rune-lexer = { path = "../rune-lexer" }
rune-ast = { path = "../rune-ast" }
rune-parser = { path = "../rune-parser" }
rune-runtime = { path = "../rune-runtime" }
rune-evaluator = { path = "../rune-evaluator" }
