[workspace]
members = [
    "crates/tint-lexer",
    "crates/tint-ast",
    "crates/tint-ir",
    "crates/tint-parser",
    "crates/tint-runtime",
    "crates/tint-semantics",
    "crates/tint-evaluator",
    "crates/tint-wasm",
    "crates/tint-cli",
]

resolver = "2"

[profile.release]
opt-level = "s"
