[workspace]
members = [
    "crates/tint-lexer",
    "crates/tint-ast",
    "crates/tint-ir",
    "crates/tint-parser",
    "crates/tint-runtime",
    "crates/tint-semantics",
    "crates/tint-evaluator",
    "crates/tint-wasm",
    "crates/tint-cli",
    "crates/tint-compiler",
    "crates/tint-analyzer",
]

resolver = "2"

[workspace.package]
version = "0.1.3"
edition = "2021"
license = "MIT"

[profile.release]
opt-level = "s"
